name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg 

    - name: Run tests
      run: poetry run pytest

    - name: Upload FFmpeg logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-logs
        path: "**/ffmpeg.log"


    - name: Upload HTML coverage report
      if: success() && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: path htmlcov/